export const commonWorkoutNames = [
  'Morning Cardio',
  'Full Body Strength',
  'Upper Body Day',
  'Lower Body Day',
  'Chest & Triceps',
  'Back & Biceps',
  'Leg Day',
  'Shoulder & Arms',
  'Core Focus',
  'HIIT Workout',
  'Yoga Session',
  'Running Session',
  'Cycling Workout',
  'Swimming',
  'Push Day',
  'Pull Day',
  'Rest Day',
  'Active Recovery',
  'Full Body Circuit',
  'Upper Body Push',
  'Upper Body Pull',
  'Legs & Glutes',
  'Cardio Blast',
  'Strength Training',
  'Endurance Training',
  'Power Training',
  'Flexibility & Mobility',
  'CrossFit WOD',
  'Bodyweight Workout',
  'Weight Training',
];

